version: '3.8'
name: time-tracker
services:
  postgres:
    image: postgres:16
    container_name: time-tracker-postgres-conteiner
    environment:
      POSTGRES_DB: time-tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5431:5432"
    restart: always