spring:
  application:
    name: time-tracker

  datasource:
    url: jdbc:postgresql://moura-time-db.postgres.database.azure.com:5432/postgres
    username: db_moura
    password: Time066@
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

  flyway:
    enabled: true

server:
  port: 8080

jwt:
  secret: your-secret-key-change-in-production-moura-tech-2026
  expiration: 86400

springdoc:
  swagger-ui:
    tags-sorter: alpha